#!/bin/sh
#
# https://www.romanzolotarev.com/bin/vol
# Copyright 2017 Roman Zolotarev <hi@romanzolotarev.com>
#
case "$1" in
  up) sndioctl output.mute=0; sndioctl output.level=+0.1 ;;
  down) sndioctl output.mute=0; sndioctl output.level=-0.1 ;;
  incup) sndioctl output.mute=0; sndioctl output.level=+0.05;;
  incdown) sndioctl output.mute=0; sndioctl output.level=-0.05;;
  max) sndioctl output.mute=0; sndioctl output.level=1 ;;
  mid) sndioctl output.mute=0; sndioctl output.level=0.5 ;;
  mute) sndioctl output.mute=1 ;;
  toggle) sndioctl output.mute=toggle ;;
  *) sndioctl output.mute=toggle ;;
esac
